var HelpIndex = [
["Apertura (definición)", "html/tall6mw7.htm"], 
["Calibración del histograma", "html/tall8vqm.htm"], 
["Cierre (definición)", "html/tall1x4b.htm"], 
["Comparación entre transformaciones del histograma", "html/tall5aye.htm"], 
["Convolución (definición)", "html/tall2t6e.htm"], 
["Cuantificación", [
["(Untitled)", "html/tall7vsl.htm"], 
["Cuantificación de una imagen", "html/tall0y5q.htm"]]], 
["Detección de contornos", "html/tall1g8e.htm"], 
["Dilatación (definición)", "html/tall2trq.htm"], 
["Ecualización del histograma", "html/tall0rjb.htm"], 
["Ejercicio de s¡ntesis", "html/tall3ry1.htm"], 
["Ejercicio de síntesis", "html/tall0o9x.htm"], 
[" parte 2", "html/tall3ywh.htm"], 
["Elemento estructurante (morfología matemática)", "html/tall39f1.htm"], 
["Erosión (definición)", "html/tall7ghh.htm"], 
["Esqueleto (definición)", "html/tall6rqb.htm"], 
["Estrechamiento (definición)", "html/tall6rqb.htm"], 
["Falso color (definición)", "html/tall9uwi.htm"], 
["Filtro de Deriche", "html/tall4lt4.htm"], 
["Filtro de Laplace", "html/tall7bhr.htm"], 
["Filtro no lineal", "html/tall1zp2.htm"], 
["Filtro promedio", "html/tall96jy.htm"], 
["Filtro promedio separable", "html/tall9f92.htm"], 
["Filtros Lineales (definición)", "html/tall2t6e.htm"], 
["Histograma (definición)", [
["Transformación del histograma (definición)", "html/tall3c1c.htm"], 
["Histograma (definición)", "html/tall36t1.htm"]]], 
["Histograma de una imagen", "html/tall7grt.htm"], 
["Imagen binaria", "html/tall2cpt.htm"], 
["Interpolación", "html/tall4mm0.htm"], 
["Introduction", "html/tall9m9i.htm"], 
["Marcado (definición)", "html/tall6ilv.htm"], 
["MeVisLab", "html/tall0epk.htm"], 
["Morfología matemática", "html/tall5rqb.htm"], 
["Negativo", "html/tall3joo.htm"], 
["Nivel de gris", "html/tall8xmg.htm"], 
["Operaciones lógicas", "html/tall8hgf.htm"], 
["Paleta de color", [
["(Untitled)", "html/tall93na.htm"], 
["Paleta de color", "html/tall899h.htm"]]], 
["Parte 1a", "html/tall5f4v.htm"], 
["Parte 1b", "html/tall7wxk.htm"], 
["Parte 2", "html/tall14vn.htm"], 
["Parte 3", "html/tall14vo.htm"], 
["Parte 4", "html/tall14vp.htm"], 
["Parte 5", "html/tall5f4x.htm"], 
["Pixel", "html/tall3xb3.htm"], 
["Producto de convolución (definición)", "html/tall2t6e.htm"], 
["Pseudo-color (definición)", "html/tall72ek.htm"], 
["Reducción (definición)", "html/tall6rqb.htm"], 
["Segmentación (definición)", "html/tall57oy.htm"], 
["Sommaire", "html/tall5jqu.htm"], 
["Suma y resta", "html/tall5x9r.htm"], 
["Síntesis", "html/tall686c.htm"], 
["Umbralización (definición)", "html/tall3h85.htm"], 
["Umbralización por histéresis et bi-umbralización", "html/tall0pyw.htm"], 
["Umbralización y otras transformaciones del histograma", "html/tall5x6d.htm"], 
["Vecindario y Conectividad", "html/tall2pme.htm"], 
["Vocabulario", "html/tall6liy.htm"]];
